### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by HurricaneJames**
Old pascal spider demo was cool. I will need to read the code to figure out how to control the spider. Right now it just wanders off the screen. It did take me a minute to figure out that "SPIDER.PAS" needed to be all caps, whereas W and R worked fine in caps or without.

### CODE REVIEW

**Comment by bradgrantham** [comment]
Thanks for testing it!  "spider.pas" in lower case works for me; what browser are you in?  Would you check it again?  Also, it moves in whatever direction the pointer is from the center of the window.

**Comment by HurricaneJames** [comment]
I was on Windows 10 64bit running Chrome. On the bus to work now. Testing on my MacBook Pro in Chrome works. Spider follows the cursor here too, though not terribly well, and at some point it crawled up my screen and started walking on an invisible ceiling :)

**Comment by bradgrantham** [comment]
When you get a chance, could you send a screen shot from WIndows after typing "spider.pas" and hitting ENTER?  Thank you!

**Comment by lkesteloot** [comment]
Strange, line 353 of IDE.js converts the string to upper case:

    workFile = workFile.toUpperCase();

I wonder why it didn't work for you. Do you mind trying it again? (And you control the spider with the mouse position. Just hover over the window to the left or right of the spider.)

**Pull request closed without merging**
